# Generated by Django 3.0.3 on 2020-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, unique=True, verbose_name='user_id')),
                ('password', models.CharField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
