# Generated by Django 3.0.3 on 2020-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
