# Generated by Django 3.0.3 on 2020-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'excel_names',
            },
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plate_No', models.IntegerField(null=True)),
                ('Replicate_No', models.IntegerField(null=True)),
                ('Well_No', models.IntegerField(null=True)),
                ('Index_No', models.IntegerField(default=0)),
                ('KaiChem_ID', models.CharField(max_length=250, null=True, verbose_name='카이참')),
                ('Conc_nM', models.IntegerField(default=0)),
                ('Cell', models.CharField(max_length=250, null=True, verbose_name='세포')),
                ('Time', models.IntegerField(default=0)),
                ('RNA_Ext_Date', models.IntegerField(default=0)),
                ('Lib_Prep_Date', models.IntegerField(default=0)),
                ('Seq_Req_Date', models.IntegerField(default=0)),
                ('NGS_Data_Date', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'excel_sheets',
            },
        ),
    ]
