# Generated by Django 3.0.3 on 2020-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_excel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
