# Generated by Django 3.0.3 on 2020-06-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20200606_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='excel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_uniq_id', to='excel.Excel'),
        ),
    ]
