# Generated by Django 3.0.3 on 2020-06-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0005_auto_20200608_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='Plate_No',
            new_name='Concentration_nM',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Well_No',
            new_name='Subset',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='Conc_nM',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='Lib_Prep_Date',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='RNA_Ext_Date',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='Seq_Req_Date',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='Time',
        ),
        migrations.AddField(
            model_name='sheet',
            name='Library_Prep_Date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='RNA_Extraction_Date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Seeding_Date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Seq_Request_Date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Treat_Time',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Well_Location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='Cell',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='Index_No',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='KaiChem_ID',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='NGS_Data_Date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='Replicate_No',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
