# Generated by Django 3.0.3 on 2020-06-29 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0006_auto_20200626_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
