# Generated by Django 3.1.2 on 2020-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_sheet_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='Cell',
            new_name='Cell_line',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Index_No',
            new_name='Compound_Name',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Concentration_nM',
            new_name='Compound_concentration_nM',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='NGS_Data_Date',
            new_name='DNA_quantity_ng',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='RNA_Extraction_Date',
            new_name='MGI_Index_No',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Seeding_Date',
            new_name='RNA_quantity_ng',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Replicate_No',
            new_name='Replicate',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Treat_Time',
            new_name='Sample_ID',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='Well_Location',
            new_name='Sample_sending_date_LAS',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='Seq_Request_Date',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='excel_name',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='name',
        ),
        migrations.AddField(
            model_name='sheet',
            name='Compound_treatment_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Plate_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='RNA_Extraction_date',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Well',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='Library_Prep_Date',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
