# Generated by Django 3.1.2 on 2020-11-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0008_auto_20201104_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='excel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel.excel'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
