# Generated by Django 3.0.3 on 2020-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0010_auto_20201105_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='DNA_quantity_ng',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
